<a href="https://colab.research.google.com/github/jonaden94/deepl-ecker-21-22/blob/main/PlaneNet/PlaneNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Clone repo
key = \
"""
-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAvcWKSRCU6cnVThYINDBAWLj0eAP3Z4jS+kMK/TW1Yb3KcjRM
x9BUHB8fTnL6SagNyScU0vzwl+jOROSOP6sUsl67Cq1YKEqdJHhY7/0oB6kZdo2N
sip75TT6dUjH31Ht5uSzfV8713MyhhITb9YtmPoPxrGJ9XzTMOYS2n97H08ibxTs
vGn6xGK8HELEQqRk9xdsBM2fA0dADLqXmoaYvs3S0ktTl6H92C77eSUv2iH45SRI
DDvcEmi4wEvw7ae2SzSYNLiwVOcP98wL2VztvRgdqVCI+9z0GTvaRD78dy1pz/DV
fexSYc9Jt/ZhSvyVwBNOCKEiaX4BPfheIkFadWBpJ1OpxbPANPVPTwcdR02hXlPm
DuMeX91o2Rc2JJZnWt9OxakYIwOQclDKg1WSTA3fC7eAoKQfEd9oc4lwmSjAVr78
si9K4wziKqVPZI4Z3kZ5E4POz/CvRFnzYrWhm4QRTq6kmltKb4mCWHKTmYen5dOF
zzJqSJjuTfJtL8qD2U1XUlEFq+7Gcx43TpxnL8ir393UJH6eYsKtz5t6fvE2CcGe
GekSTKckw8QHkR/yF01RWlEjGTVtSmy2ZY7ifkp9VUyHzshUntsRAXMZ1bJsglRA
z6L/hTOi2wwiPCzKCdbIs7OB98PciE3ZTdVJC+fn7KkNjhkt6JxqQgkANzkCAwEA
AQKCAgEAikgGcyVFDXKIHwVI5xZ93OixIz7oqaX27mup90aKq/VLLprTlApHL9Kx
0k1P+hoeKYRz1SaA/oCixWqyCMzWIP+MVcRoZ7uu9CNJ015qK+LZbhzJspjofOV0
17+3/Q/LRiNCc0nQ5jbICw/i3+x2f3E/y64U9DAICCqudE7OXcshMUZTFxw2oaG8
pu8z6ce21qJXkMxwYUgq8NuKmwwXA3ohdCF1gRmGSmA52FXzn4R/xCEC6v83Zqau
cVkk71f1KqnhexFVVBim9w7VV4cyqUaIXpcTqkugBz8o1e/7sbAC2YYJW1+3zBPr
CMTcsnKJgFPQ2dLoq2wo5Yo0tctfaMRezhpLquIYJlg190IN53aTPvIExBj+N+DW
Tg4WfSLoYH/zD7/o3mr8yW2n3RhD6D0GJH1NkwP0mlpA2QprYpR0F5QZQAi1R5KA
6kAgWkgJD7duSkLGSurtTENgMv+dXhu7ZB2iPioiGcx548gu9iXLuJMe/C4wiwlt
HbiY4qRHLffoCY/u/VCraTJY+6iW0Xu0VUwe2QBrXJsuSX1kWdkpADyfjkPyr6o/
AbOqpxMjyqDKEIXd9jyfeUTKN8IyFHvLP3eTshUAKqA6CAA4h1NPkvz1bLLsMRG3
E6mziKRen5+I1EIZPOHhipmsXBxtiPzo8l45R2UjmaIFWLBn3Y0CggEBAOxPCiNn
geoATBABfklCWkydO9ac4956eFDp0ZDRU2rQ/9uzRPeQ92VmaRvYxO9Ijqmhu80J
nYCs/1XVeUkxMXwcJhrSeSNMQ20urWJTDCdJMCm1tZxIbsFaAipA9a/H6HXZBP3Y
IOY/G5Th4WIPbG41mMqGqwWogYNZ6frtax1kp8SJNcDqvTXgIIbs2zgo9sOrKom9
3i54fuwJ+loWzgKj6yd5eGif9gzuCGVpO+RpXOvrQppytjVOQr9CU9Z8OJPF5QAS
vmuluqrKVrCD8gx3mEHJIhhoixoNfJbrti+D49gByKBsI6UtlfnKL/RR4WYxuLLQ
rplsrVJfEJawS9MCggEBAM2VxEJn8bTWX8MICF/zdXwVTABO4GYGvCX40HJ0WIaT
t0O5RFOrbamQt8Umm13h6UIs9DVEh2UKhgjLBwNq5tNY65mP+TZAVVug33gpHDyI
lIHNLxQQYFTUd4FrFW95vpX7bx5tqpCEMic+gfp+9ruHHq/6s3ccfBq6/1e8hQ39
lgJq9odoPj1BuSMTSgZ/foHnEA+oLnDCsg+8wFWYQGBC3sj5qP5IqpP7J0bbpQRT
M+eA69YyUvVIj1QapP9yFslxYjpPef8FD6llveQdIvxZpqMYykG6TzDU/5dAmYN2
JetY8dhyg96e7R85aIyNcg8ReQG3iHzDeT1NLJSRxUMCggEAeAJwEKjphnBeMKbB
fu0OtOgJUqXc58jkv5rvjg9wwMehmO8DMINT0RBggv7kjO0ZXra/jJK8hXPWPL4s
WWp9Sh11kJuhX7bEa3eQIGYyvuTha91XfSYf8VwHy3OwEnSA7xCnA0+27ZfRJxxL
/SP+Gj5n+TrJMhdwpseMF55pjsTmmt5gCThtnSXU/xDdCDltkNOlx8xAQPN66d7r
YMNCHn8m1qZO6zuJlulwJCh8fTSxNzMEYTGurYWwSjeiIkR16z5OXWongL3q/f/C
ZOStkX1POuGtyh2Vv0ZoJrFQlfLyTGojfK1OsP1ktDXlgrvur5rCxTVL5qkVoMac
wxqHdwKCAQAjRYrCieriR9VuNLabH74MZ+r+Moo1dvpY2XOJ74Qwsq9Co0qhwEu0
R+v/mzwUw2mtvOC5MuS35TJR1+OAJpsrr5ncYuMy956tddBhYUxC5nv0OSvWmWit
pTZLsf+ffJfCS70oz0/wM34XVZYfUCEs02Xkc3LPAMgaHfMpLmL1n4hZKdjaKnxj
Lh+BcRHGQ6GE0AvlY8lz9zNtl8i35sNEwLRQbuUbm4QIl5KJia2qLEw/b9MGkOPC
yYwttdSRLxXRwe5EatZXdprVSWtm88jI2ujIGry4wipMCn8/iAnOkDq5Qi1cIWmW
jFXKgaL6WlozU6AbN03nefIXHmKDqu7ZAoIBAGiIJOk7o4VeEB5xP8PXqrZofHBB
47rBlaH2ajtSBSTip31e++3iIBmZvvKu2lLEQXKny+1cJgCbl0ICTducoB6r7ARL
U4xbotNgQIyKsMn9rQttqzHVYpbwe1j/eWok5DuRkBuc3Nlcl4B3nPsLD1GKB/QM
x/rPv4T8Accr5czgzNZEJfkuI4/9za5gA3ltS90+kJU1IszZxMseuxc7yLEsjAi5
2y301P1rqMdQ7xg6JXCjh3yPxQ0ug2ZykFh1X9+DwG86Belqlh56W/nFl298IkTG
KIVWo9C9mDm8hm0TGim2KOKNP5rkj7ndETB1S57qi+1amSaGXOcBbLAGzuQ=
-----END RSA PRIVATE KEY-----
"""

!mkdir -p /root/.ssh
with open(r'/root/.ssh/id_rsa', 'w', encoding="utf8") as fh:
    fh.write(key)
!ssh-keyscan github.com >> /root/.ssh/known_hosts
!chmod 644 /root/.ssh/known_hosts
!chmod 600 /root/.ssh/id_rsa
!ssh -T git@github.com
!git clone git@github.com:jonaden94/treelearning.git

# github.com:22 SSH-2.0-babeld-fb957b4d
# github.com:22 SSH-2.0-babeld-fb957b4d
# github.com:22 SSH-2.0-babeld-fb957b4d
Hi jonaden94/treelearning! You've successfully authenticated, but GitHub does not provide shell access.
Cloning into 'treelearning'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (429/429), done.
remote: Total 505 (delta 288), reused 213 (delta 68), pack-reused 0
Receiving objects: 100% (505/505), 31.01 MiB | 5.89 MiB/s, done.
Resolving deltas: 100% (288/288), done.


In [63]:
#@title Pull repo
%cd treelearning/
!git pull 

%cd ..

/content/treelearning
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 30 (delta 16), reused 11 (delta 0), pack-reused 0
Unpacking objects: 100% (30/30), done.
From github.com:jonaden94/treelearning
   1386b3f..7cc46f3  main                  -> origin/main
   576d85d..08dcfab  datautilsandtransform -> origin/datautilsandtransform
Updating 1386b3f..7cc46f3
Fast-forward
 PointNet.ipynb                           | 281 +++++++++++++++++++++++--------
 pretrained models/pointnet_good model.pt | Bin 0 -> 3471541 bytes
 python/data_utils.py                     |   4 +-
 python/exploration2.py                   |  10 +-
 python/testfile.py                       |   6 +-
 python/train_utils.py                    |  23 ++-
 python/transform.py                      |   3 +-
 7 files changed, 236 insertions(+), 91 deletions(-)
 create mode 100644 pretrained models/pointnet_good model.pt
/content


In [84]:
#@title Mount
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
root_dir = "/content/drive/MyDrive/Colab/PointNet3D"
utils_dir = "/content/treelearning/PlaneNet"


Mounted at /content/drive


In [85]:
#@title Imports
!pip install path.py;
from path import Path
import sys
sys.path.append(root_dir)
sys.path.append(utils_dir)
import plotly.graph_objects as go
import numpy as np
import scipy.spatial.distance
import math
import random
import PlaneNetUtils

In [90]:
# set device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [34]:
# define methods from PlaneNetUtils.py
cent_norm = PlaneNetUtils.Normalize()
rotation_z = PlaneNetUtils.RandRotation_z()
add_noise = PlaneNetUtils.RandomNoise()

In [86]:
# define functions to be used below
import random

def read_pts(file):
    verts = np.genfromtxt(file)
    return cent_norm(verts)
    #return verts

def read_seg(file):
    verts = np.genfromtxt(file, dtype= (int))
    return verts

def sample_2000(pts, pts_cat):    
    res1 = np.concatenate((pts,np.reshape(pts_cat, (pts_cat.shape[0], 1))), axis= 1)
    res = np.asarray(random.choices(res1, weights=None, cum_weights=None, k=2000))
    images = res[:, 0:3]
    categories = res[:, 3]
    categories-=np.ones(categories.shape)
    return images, categories

## Model

In [36]:
import torch
import torch.nn as nn
import numpy as np
import torch.nn.functional as F

class Tnet(nn.Module):
   def __init__(self, k=3):
      super().__init__()
      self.k=k
      self.conv1 = nn.Conv1d(k,64,1)
      self.conv2 = nn.Conv1d(64,128,1)
      self.conv3 = nn.Conv1d(128,1024,1)
      self.fc1 = nn.Linear(1024,512)
      self.fc2 = nn.Linear(512,256)
      self.fc3 = nn.Linear(256,k*k)

      self.bn1 = nn.BatchNorm1d(64)
      self.bn2 = nn.BatchNorm1d(128)
      self.bn3 = nn.BatchNorm1d(1024)
      self.bn4 = nn.BatchNorm1d(512)
      self.bn5 = nn.BatchNorm1d(256)
       

   def forward(self, input):
      # input.shape == (bs,n,3)
      bs = input.size(0)
      xb = F.relu(self.bn1(self.conv1(input)))
      xb = F.relu(self.bn2(self.conv2(xb)))
      xb = F.relu(self.bn3(self.conv3(xb)))
      pool = nn.MaxPool1d(xb.size(-1))(xb)
      flat = nn.Flatten(1)(pool)
      xb = F.relu(self.bn4(self.fc1(flat)))
      xb = F.relu(self.bn5(self.fc2(xb)))
      
      #initialize as identity
      init = torch.eye(self.k, requires_grad=True).repeat(bs,1,1)
      if xb.is_cuda:
        init=init.cuda()
      matrix = self.fc3(xb).view(-1,self.k,self.k) + init
      return matrix


class Transform(nn.Module):
   def __init__(self):
        super().__init__()
        self.input_transform = Tnet(k=3)
        self.feature_transform = Tnet(k=128)
        self.fc1 = nn.Conv1d(3,64,1)
        self.fc2 = nn.Conv1d(64,128,1) 
        self.fc3 = nn.Conv1d(128,128,1)
        self.fc4 = nn.Conv1d(128,512,1)
        self.fc5 = nn.Conv1d(512,2048,1)

        
        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(128)
        self.bn4 = nn.BatchNorm1d(512)
        self.bn5 = nn.BatchNorm1d(2048)

   def forward(self, input):
        n_pts = input.size()[2]
        matrix3x3 = self.input_transform(input)
        xb = torch.bmm(torch.transpose(input,1,2), matrix3x3).transpose(1,2)
        outs = []
        
        out1 = F.relu(self.bn1(self.fc1(xb)))
        outs.append(out1)
        out2 = F.relu(self.bn2(self.fc2(out1)))
        outs.append(out2)
        out3 = F.relu(self.bn3(self.fc3(out2)))
        outs.append(out3)
        matrix128x128 = self.feature_transform(out3)
        
        out4 = torch.bmm(torch.transpose(out3,1,2), matrix128x128).transpose(1,2) 
        outs.append(out4)
        out5 = F.relu(self.bn4(self.fc4(out4)))
        outs.append(out5)
       
        xb = self.bn5(self.fc5(out5))
        
        xb = nn.MaxPool1d(xb.size(-1))(xb)
        out6 = nn.Flatten(1)(xb).repeat(n_pts,1,1).transpose(0,2).transpose(0,1)#.repeat(1, 1, n_pts)
        outs.append(out6)
        
        
        return outs, matrix3x3, matrix128x128


class PointNetSeg(nn.Module):
    def __init__(self, classes = 10):
        super().__init__()
        self.transform = Transform()

        self.fc1 = nn.Conv1d(3008,256,1) 
        self.fc2 = nn.Conv1d(256,256,1) 
        self.fc3 = nn.Conv1d(256,128,1) 
        self.fc4 = nn.Conv1d(128,4,1) 
        

        self.bn1 = nn.BatchNorm1d(256)
        self.bn2 = nn.BatchNorm1d(256)
        
        self.bn3 = nn.BatchNorm1d(128)
        self.bn4 = nn.BatchNorm1d(4)
        
        self.logsoftmax = nn.LogSoftmax(dim=1)
        

    def forward(self, input):
        inputs, matrix3x3, matrix128x128 = self.transform(input)
        stack = torch.cat(inputs,1)
        
        xb = F.relu(self.bn1(self.fc1(stack)))
       
        xb = F.relu(self.bn2(self.fc2(xb)))
    
        xb = F.relu(self.bn3(self.fc3(xb)))
        
        output = F.relu(self.bn4(self.fc4(xb)))
        
        return self.logsoftmax(output), matrix3x3, matrix128x128



## Dataset

In [73]:
from __future__ import print_function, division
import os
import torch
import pandas as pd
from skimage import io, transform
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
from torch.utils.data.dataset import random_split
import PlaneNetUtils

class Data(Dataset):
    """Face Landmarks dataset."""

    def __init__(self, root_dir, valid=False, transform=None, small=True):
        
        self.root_dir = root_dir
        self.files = []
        self.valid=valid

        newdir = root_dir + '/expert_verified/points_label/'
        listdir = os.listdir(newdir)

        if small:
            listdir = listdir[:100]
            
        for file in listdir:
            o = {}
            o['category'] = newdir + file
            o['img_path'] = root_dir + '/points/'+ file.replace('.seg', '.pts')
            self.files.append(o)
       

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img_path = self.files[idx]['img_path']
        category = self.files[idx]['category']
        with open(img_path, 'r') as f:
            image1 = read_pts(f)
        with open(category, 'r') as f:  
            category1 = read_seg(f)
        image2, category2 = sample_2000(image1, category1)
        if not self.valid:
            image2 = rotation_z(add_noise(image2))
        
        return {'image': np.array(image2, dtype="float32"), 'category': category2.astype(int)}


In [74]:
dset = Data(root_dir , transform=None)
train_num = int(len(dset) * 0.95)
val_num = int(len(dset) *0.05)
if int(len(dset)) - train_num -  val_num >0 :
    train_num = train_num + 1
elif int(len(dset)) - train_num -  val_num < 0:
    train_num = train_num -1
#train_dataset, val_dataset = random_split(dset, [3000, 118])
train_dataset, val_dataset = random_split(dset, [train_num, val_num])
val_dataset.valid=True

print('######### Dataset class created #########')
print('Number of images: ', len(dset))
print('Sample image shape: ', dset[0]['image'].shape)
#print('Sample image points categories', dset[0]['category'], end='\n\n')

train_loader = DataLoader(dataset=train_dataset, batch_size=64)
val_loader = DataLoader(dataset=val_dataset, batch_size=64)

#dataloader = torch.utils.data.DataLoader(dset, batch_size=4, shuffle=True, num_workers=4)

######### Dataset class created #########
Number of images:  100
Sample image shape:  (2000, 3)


## Training loop

In [87]:
def pointnetloss(outputs, labels, m3x3, m128x128, alpha = 0.0001):
    criterion = torch.nn.NLLLoss()
    bs=outputs.size(0)
    id3x3 = torch.eye(3, requires_grad=True).repeat(bs,1,1)
    id128x128 = torch.eye(128, requires_grad=True).repeat(bs,1,1)
    if outputs.is_cuda:
        id3x3=id3x3.cuda()
        id128x128=id128x128.cuda()
    diff3x3 = id3x3-torch.bmm(m3x3,m3x3.transpose(1,2))
    diff128x128 = id128x128-torch.bmm(m128x128,m128x128.transpose(1,2))
    return criterion(outputs, labels) + alpha * (torch.norm(diff3x3)+torch.norm(diff128x128)) / float(bs)
        

In [88]:
def train(model, train_loader, val_loader=None,  epochs=15, save=True):
    for epoch in range(epochs): 
        pointnet.train()
        running_loss = 0.0
        for i, data in enumerate(train_loader, 0):
            inputs, labels = data['image'].to(device), data['category'].to(device)
            optimizer.zero_grad()
            outputs, m3x3, m64x64 = pointnet(inputs.transpose(1,2))

            loss = pointnetloss(outputs, labels, m3x3, m64x64)
            loss.backward()
            optimizer.step()

            # print statistics
            running_loss += loss.item()
            if i % 10 == 9:    # print every 10 mini-batches
                    print('[%d, %5d] loss: %.3f' %
                        (epoch + 1, i + 1, running_loss / 10))
                    running_loss = 0.0

        pointnet.eval()
        correct = total = 0

        # validation
        if val_loader:
            with torch.no_grad():
                for data in val_loader:
                    inputs, labels = data['image'].to(device), data['category'].to(device)
                    outputs, __, __ = pointnet(inputs.transpose(1,2))
                    _, predicted = torch.max(outputs.data, 1)
                    total += labels.size(0) * labels.size(1) ##
                    correct += (predicted == labels).sum().item()
            val_acc = 100 * correct / total
            print('Validation accuracy: %d %%' % val_acc)

        # save the model
        if save:
            torch.save(pointnet.state_dict(), "/content/treelearning/PlaneNet/state_dicts/plane_dict"+str(epoch)+"_"+str(val_acc))


In [89]:
# define model and train
pointnet = PointNetSeg()
pointnet = pointnet.to(device)
optimizer = torch.optim.Adam(pointnet.parameters(), lr=0.001)
train(pointnet, train_loader, val_loader,  save=True, epochs=10)

Valid accuracy: 29 %
Valid accuracy: 28 %
Valid accuracy: 35 %
Valid accuracy: 35 %
Valid accuracy: 40 %
Valid accuracy: 36 %
Valid accuracy: 39 %
Valid accuracy: 38 %
Valid accuracy: 41 %
Valid accuracy: 43 %


## test

In [ ]:
pointnet = PointNetSeg()
pointnet.load_state_dict(torch.load("/content/treelearning/PlaneNet/state_dicts/plane_dict9_57.53"))
pointnet.eval()

In [97]:
batch = next(iter(val_loader))
pred = pointnet(batch['image'].transpose(1,2))
pred_np = np.array(torch.argmax(pred[0],1));
pred_np

array([[0, 0, 0, ..., 0, 1, 0],
       [2, 1, 1, ..., 2, 2, 3],
       [0, 1, 2, ..., 2, 0, 0],
       [0, 0, 0, ..., 2, 1, 0],
       [2, 1, 0, ..., 2, 2, 2]])

In [117]:
pred_np==np.array(batch['category'])

array([[ True,  True, False, ...,  True, False,  True],
       [False,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False,  True, False],
       [False,  True,  True, ..., False, False,  True]])

In [118]:
acc = (pred_np==np.array(batch['category']))

In [120]:
resulting_acc = np.sum(acc, axis=1) / 2000

In [123]:
resulting_acc

array([0.502 , 0.521 , 0.6285, 0.5705, 0.571 ])

In [124]:
# true
x,y,z=np.array(batch['image'][0]).T
c = np.array(batch['category'][0]).T

fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, 
                                   mode='markers',
                                   marker=dict(
        size=30,
        color=c,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=1.0
    ))])
fig.update_traces(marker=dict(size=2,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

In [129]:
# prediction
x,y,z=np.array(batch['image'][0]).T
c = np.array(pred_np[0]).T

fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, 
                                   mode='markers',
                                   marker=dict(
        size=30,
        color=c,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=1.0
    ))])
fig.update_traces(marker=dict(size=2,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

In [128]:
pred_np[0]

array([0, 0, 0, ..., 0, 1, 0])